name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master   # or main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Zip source bundle
        run: zip -r deploy.zip . -x '*.git*' 'node_modules/*' '.github/*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v25
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: grafana-example-api
          environment_name: grafana-example-api-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
